changelog:
  exclude:
    labels:
      - ignore-for-release

  categories:
    - title: ☢️ Security
      labels:
        - security
        - vulnerability

    - title: 💥 Breaking Changes
      labels:
        - breaking
        - breaking-change

    - title: 🎉 New Features
      labels:
        - feature

    - title: 💅 Enhancements
        - enhancement

    - title: 🐛 Bug Fixes
      labels:
        - bug
        - bugfix

    - title: 📦 Dependencies
      labels:
        - dependencies

    - title: ✨ Miscellaneous Changes
      labels:
        - "*"
