changelog:
  exclude:
    labels:
      - ignore-for-release

  categories:
    - title: ☢️ Security
      labels:
        - bugfix

    - title: 💥 Breaking Changes
      labels:
        - breaking-change

    - title: 🎉 New Features
      labels:
        - enhancement

    - title: 🐛 Bug Fixes
      labels:
        - bugfix

    - title: 🧩 Dependencies
      labels:
        - dependencies

    - title: Other Changes
      labels:
        - "*"
