name: Feature Request
description: Suggest a new feature
labels: [enhancement]
assignees:
  - MiguelRipoll23
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest new features!
  - type: textarea
    id: feature-description
    attributes:
      label: What are you missing?
      description: A description of the feature suggested to be added
    validations:
      required: true
