name: Deploy plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Change directory
        run: /var/lib/homebridge/node_modules

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install plugin
        run: /opt/homebridge/bin/npm install
