name: Deploy plugin

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure path
        run: export PATH="$PATH:/opt/homebridge/bin"

      - name: Install plugin
        run: /opt/homebridge/bin/npm install
