name: Publish package (npm)

on:
  release:
    types: [published]

jobs:
  install-package:
    name: Install package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

        with:
          cache: "npm"
          registry-url: https://registry.npmjs.org/

      - name: Install package
        run: npm ci

  publish-package:
    name: Publish package
    runs-on: ubuntu-latest
    needs: [install-package]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

        with:
          registry-url: https://registry.npmjs.org/

      - name: Get version
        run: |
          echo "NPM_VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV

      - name: Publish package

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        run: |
          npm publish --access public --tag "$(if [[ $NPM_VERSION == *-* ]]; then echo beta; else echo latest; fi)"
