name: Publish package

on:
  push:
    tags:
      - 'v*'
      
jobs:
  publish-npm:
    name: Publish package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org/

    - name: Get package version
      env:
        TAG_REF: ${{ github.ref }}

