name: Publish package

on:
  release:
    types: [published]

jobs:
  publish-package:
    name: Publish package
    uses: MiguelRipoll23/global/.github/workflows/publish-package.yml@main

    with:
      node-version: 16

    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
