name: Publush package

on:
  push:
    tags:
      # https://semver.org/ proper release tags, more or less
      - v[0-9]+.[0-9]+.[0-9]+
      # prerelease tags, more or less
      - v[0-9]+.[0-9]+.[0-9]+-*
      
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org/

    - name: Get package version
      env:
        TAG_REF: ${{ github.ref }}

    - name: Publish package
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        TAG_REF: ${{ github.ref }}
      run: >-
        npm publish --access public --tag "$(if [[ $TAG_REF == *-* ]]; then echo beta; else echo latest; fi)"
