name: Publish package

on:
  push:
    tags:
      # https://semver.org/ proper release tags, more or less
      - 'v[0-9]+.[0-9]+.[0-9]+'
      # prerelease tags, more or less
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
      
jobs:
  publish-npm:
    name: Publish package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org/

    - name: Get version
      run: |
        echo "NPM_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    - name: Update version
      run: |
        npm version $NPM_VERSION --no-git-tag-version

    - name: Commit and push
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish package
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        TAG_REF: ${{ github.ref }}
      run: |
        npm publish --access public --tag "$(if [[ $NPM_VERSION == *-* ]]; then echo beta; else echo latest; fi)"
