name: Update version

on:
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        default: stable
        description: Pick channel
        options:
          - alpha
          - beta
          - stable

      new-build-for-prerelease:
        type: boolean
        default: true
        description: New build for prerelease

jobs:
  update-version:
    name: Update version name
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Generate tag name
        uses: MiguelRipoll23/generate-tag-name@v1.0.0
        id: generate-tag-name
        with:
          channel: ${{ inputs.channel }}

      - name: Update version name
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ steps.generate-tag-name.outputs.tag-name }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: version/${{ steps.generate-tag-name.outputs.tag-name }}
          commit-message: ${{ steps.generate-tag-name.outputs.tag-name }}
          title: Bump version to ${{ steps.generate-tag-name.outputs.tag-name }}
          body: Automated pull request triggered by a new version update.
          labels: ignore-for-release
